version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: note_taking_db
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  testdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: note_taking_db
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3307:3306"
    volumes:
      - test_data:/var/lib/mysql
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  test_data:
